"""add statement to status table

Revision ID: 3b326ec0f722
Revises: b0f59a923891
Create Date: 2020-02-11 13:13:58.920289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b326ec0f722'
down_revision = 'b0f59a923891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('statement', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'statement')
    # ### end Alembic commands ###
