"""initial aut0 generate

Revision ID: b0f59a923891
Revises: 1208eae0d6eb
Create Date: 2020-02-11 13:12:35.118131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f59a923891'
down_revision = '1208eae0d6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
